"""1C TestClient protocol research and runtime components."""

from .evidence import (
    AcceptanceStatus,
    OperationDescriptor,
    get_readonly_operation_descriptor,
    list_readonly_operation_descriptors,
    load_accepted_mappings,
)
from .bootstrap import CaptureBootstrap, resolve_capture_dir
from .frames import (
    CLIENT_TO_MANAGER,
    MANAGER_TO_CLIENT,
    TAIL_MARKER,
    adapt_manager_header_guid,
    extract_client_ack_guid,
    extract_managed_form_guid,
    manager_frame_sequence,
    payload_summary,
    sha256_hex,
    split_tail_marker,
    strip_tail,
)
from .templates import BootstrapFrameRenderer, ProtocolTemplates, RenderedFrame
from .lifecycle import (
    TestClientProcess,
    TestClientTarget,
    attach_test_client,
    ensure_test_client,
    launch_test_client,
    load_env_file,
    pick_free_display,
    stop_by_pid,
    stop_test_client,
)
from .screenshot import ScreenshotError, capture_screenshot, get_backend
from .session import (
    ActiveFormContext,
    ActiveWindowContext,
    FormElementDetailsContext,
    FormSummaryContext,
    InitialUiContext,
    SessionHandle,
    TestClientSession,
    read_available,
    timestamp_name,
    utc_now,
)

__all__ = [
    "AcceptanceStatus",
    "ActiveFormContext",
    "ActiveWindowContext",
    "BootstrapFrameRenderer",
    "CLIENT_TO_MANAGER",
    "CaptureBootstrap",
    "FormElementDetailsContext",
    "FormSummaryContext",
    "InitialUiContext",
    "MANAGER_TO_CLIENT",
    "OperationDescriptor",
    "ProtocolTemplates",
    "RenderedFrame",
    "ScreenshotError",
    "TAIL_MARKER",
    "TestClientProcess",
    "TestClientSession",
    "TestClientTarget",
    "adapt_manager_header_guid",
    "attach_test_client",
    "capture_screenshot",
    "ensure_test_client",
    "get_backend",
    "launch_test_client",
    "load_env_file",
    "pick_free_display",
    "stop_by_pid",
    "stop_test_client",
    "extract_client_ack_guid",
    "extract_managed_form_guid",
    "get_readonly_operation_descriptor",
    "list_readonly_operation_descriptors",
    "load_accepted_mappings",
    "manager_frame_sequence",
    "payload_summary",
    "read_available",
    "resolve_capture_dir",
    "sha256_hex",
    "split_tail_marker",
    "strip_tail",
    "timestamp_name",
    "utc_now",
]
