"""Stable public extension surface for standalone and downstream qa-mcp runtimes."""

from .application import (
    ApplicationContext,
    activate_application_context,
    bind_application_context,
    current_application_context,
    set_default_application_context,
)
from .boundary import (
    EvidenceLedger,
    EvidenceReceipt,
    EvidenceScope,
    OperationBoundaryError,
    OperationFieldClass,
    OperationProvenance,
    admit_operation_provenance,
    normalize_operation_result,
)
from .contracts import (
    ArtifactReference,
    OperationError,
    OperationKind,
    OperationRequest,
    OperationResult,
    OperationVerdict,
    QAExecutor,
    SessionIdentity,
    TargetIdentity,
)
from .executors import HandlerQAExecutor, LocalQAExecutor, WindowsHostQAExecutor
from .operations import (
    NATIVE_SESSION_OPERATION_NAMES,
    blocked_bound_route,
    execute_mcp_operation,
    execute_operation,
    execute_scenario_operation,
    is_explicitly_unbound_context,
)
from .runtime_target import (
    EvidencePolicy,
    ProviderTargetProfile,
    RuntimeFingerprint,
    RuntimeTargetBinding,
    RuntimeTargetBindingError,
    RuntimeTargetObservation,
    RuntimeTargetResolution,
    resolve_runtime_target,
    runtime_target_readiness,
    validate_runtime_target_resolution,
)

__all__ = [
    "ApplicationContext",
    "ArtifactReference",
    "EvidencePolicy",
    "EvidenceLedger",
    "EvidenceReceipt",
    "EvidenceScope",
    "HandlerQAExecutor",
    "LocalQAExecutor",
    "NATIVE_SESSION_OPERATION_NAMES",
    "OperationError",
    "OperationBoundaryError",
    "OperationFieldClass",
    "OperationKind",
    "OperationRequest",
    "OperationResult",
    "OperationVerdict",
    "OperationProvenance",
    "QAExecutor",
    "ProviderTargetProfile",
    "RuntimeFingerprint",
    "RuntimeTargetBinding",
    "RuntimeTargetBindingError",
    "RuntimeTargetObservation",
    "RuntimeTargetResolution",
    "SessionIdentity",
    "TargetIdentity",
    "WindowsHostQAExecutor",
    "activate_application_context",
    "admit_operation_provenance",
    "bind_application_context",
    "blocked_bound_route",
    "current_application_context",
    "execute_mcp_operation",
    "execute_operation",
    "execute_scenario_operation",
    "is_explicitly_unbound_context",
    "normalize_operation_result",
    "resolve_runtime_target",
    "runtime_target_readiness",
    "validate_runtime_target_resolution",
    "set_default_application_context",
]
