#!/usr/bin/env python3
"""CLI wrapper for the direct Python TestManager prototype."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from python_manager_client import (
    CaptureBootstrap,
    ProtocolTemplates,
    TestClientSession,
    repo_root_from_script,
    resolve_capture_dir,
    timestamp_name,
    utc_now,
)
from qa_mcp.protocol.bootstrap_synth import synthesize_bootstrap


def run_probe(args: argparse.Namespace) -> dict[str, Any]:
    repo_root = repo_root_from_script()
    capture_dir = resolve_capture_dir(args.capture_dir, repo_root)
    bootstrap = CaptureBootstrap.load(capture_dir)
    templates = ProtocolTemplates.load(args.manager_templates.resolve())

    if args.randomize_constant_names:
        randomize: bool | list[str] = [n.strip() for n in args.randomize_constant_names.split(",") if n.strip()]
    else:
        randomize = bool(args.randomize_constants)
    synthesized = synthesize_bootstrap(randomize_constants=randomize) if args.synthesize_bootstrap else None

    output_dir = args.output_dir
    if output_dir is None:
        output_dir = repo_root / "runtime" / "protocol-research" / "python-manager-probe" / timestamp_name()
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "schema": "python-manager-probe.manifest.v1",
        "started_at": utc_now(),
        "query": args.query,
        "capture_dir": str(capture_dir),
        "templates": str(templates.path),
        "target_host": args.host,
        "target_port": args.port,
        "output_dir": str(output_dir),
        "synthesize_bootstrap": bool(args.synthesize_bootstrap),
        "synthesized_counter_base": synthesized.counter_base if synthesized else None,
        "synthesized_ticket_guid": synthesized.ticket_guid.hex() if synthesized else None,
    }
    (output_dir / "probe_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    with TestClientSession(
        host=args.host,
        port=args.port,
        connect_timeout_sec=args.connect_timeout_sec,
        read_timeout_sec=args.read_timeout_sec,
        idle_timeout_sec=args.idle_timeout_sec,
    ) as session:
        if args.query == "initial-ui":
            context = session.get_initial_ui_context(bootstrap=bootstrap, templates=templates, output_dir=output_dir)
        elif args.query == "active-window-context":
            context = session.get_active_window_context(
                bootstrap=bootstrap, templates=templates, output_dir=output_dir, synthesized=synthesized
            )
        elif args.query == "active-form-context":
            context = session.get_active_form_context(bootstrap=bootstrap, templates=templates, output_dir=output_dir)
        elif args.query == "form-summary":
            context = session.get_form_summary(bootstrap=bootstrap, templates=templates, output_dir=output_dir)
        elif args.query == "form-element-details":
            context = session.get_form_element_details(
                bootstrap=bootstrap,
                templates=templates,
                output_dir=output_dir,
                frame_mode=args.element_frame_mode,
            )
        else:
            raise ValueError(f"Unsupported query: {args.query}")

    result = context.to_result()
    (output_dir / "python_manager_probe_result.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=15381)
    parser.add_argument("--capture-dir", default="20260602-084433")
    parser.add_argument(
        "--query",
        choices=("initial-ui", "active-window-context", "active-form-context", "form-summary", "form-element-details"),
        default="initial-ui",
    )
    parser.add_argument(
        "--element-frame-mode",
        choices=("short", "full"),
        default="short",
        help="Frame schedule for form-element-details: short sends 1..17,101..106; full sends 1..106.",
    )
    parser.add_argument(
        "--manager-templates",
        type=Path,
        required=True,
        help="manager_frame_templates.json generated by extract_manager_templates.py.",
    )
    parser.add_argument(
        "--synthesize-bootstrap",
        action="store_true",
        help="Card 62/73: render manager frames 1..7 from the in-repo synthesizer (no captured bytes)",
    )
    parser.add_argument(
        "--randomize-constants",
        action="store_true",
        help="With --synthesize-bootstrap: replace ALL lab/config-constant GUIDs with fresh ones "
        "(proves they are manager-free-choice for full portability)",
    )
    parser.add_argument(
        "--randomize-constant-names",
        default="",
        help="Comma-separated subset of constants to randomize (session_guid,token_7f,guid2); "
        "overrides --randomize-constants when set",
    )
    parser.add_argument("--connect-timeout-sec", type=float, default=10.0)
    parser.add_argument("--read-timeout-sec", type=float, default=5.0)
    parser.add_argument("--idle-timeout-sec", type=float, default=0.25)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = run_probe(args)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(f"status={result['status']}")
        print(f"output_dir={result['output_dir']}")
        print(f"sent_byte_count={result['sent_byte_count']}")
        print(f"received_byte_count={result['received_byte_count']}")
        if result.get("active_form_name"):
            print(f"active_form_name={result['active_form_name']}")
        if result.get("active_form_caption"):
            print(f"active_form_caption={result['active_form_caption']}")
        if result.get("active_window_ref"):
            print(f"active_window_ref={result['active_window_ref']}")
        if result.get("element_count") is not None:
            print(f"element_count={result['element_count']}")
        if result.get("element_detail_count") is not None:
            print(f"element_detail_count={result['element_detail_count']}")
        if result.get("frame_mode"):
            print(f"frame_mode={result['frame_mode']}")
        for frame in result["frames"]:
            print(f"frame={frame['send_index']} semantic={frame['semantic_guess']} bytes={frame['response_byte_count']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
