"""Build a full API scope tracker for the protocol corpus.

Unlike ``coverage_report.py`` (which details only mapped members), the scope
tracker lists *every* inventory member (the full 160-member denominator) with
its current status, so progress toward 100% is visible at a glance.

Status per member uses the same taxonomy as the coverage report:

- ``accepted_reviewed``: accepted proof with a reviewed case-to-API mapping.
- ``accepted_seed``: accepted proof but the correspondence is still a seed.
- ``candidate``: non-accepted evidence references the member.
- ``uncovered``: nothing references the member yet.

It joins two evidence sources and keeps the strongest bucket per member:

- ``case-api-map.json`` (read-only / safe-action correspondences), and
- ``mutation-evidence-map.json`` (status contributed by real mutation work).

The tool fails closed when either source references an API member that does not
exist in the inventory.
"""

from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from pathlib import Path

# Reuse the coverage-report machinery so there is a single source of truth for
# inventory parsing, mapping classification and bucket ordering.
from coverage_report import (  # type: ignore
    BUCKET_ORDER,
    DEFAULT_CASE_MAP,
    DEFAULT_INVENTORY,
    build_coverage,
    load_json,
    percent,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MUTATION_EVIDENCE = (
    REPO_ROOT
    / "docs"
    / "protocol-research"
    / "api-inventory"
    / "mutation-evidence-map.json"
)
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "protocol-research" / "scope-tracker.md"


def apply_mutation_evidence(result: dict, mutation_evidence: dict) -> list[str]:
    """Merge mutation-evidence buckets into coverage, keeping the strongest.

    Returns the list of mutation-evidence members that do not exist in the
    inventory (callers fail closed when this is non-empty).
    """

    coverage = result["coverage"]
    unmatched: list[str] = []
    for member in mutation_evidence.get("members", []):
        api = member.get("api")
        bucket = member.get("bucket", "candidate")
        if api not in coverage:
            unmatched.append(api)
            continue
        if bucket not in BUCKET_ORDER:
            raise ValueError(f"unknown mutation-evidence bucket: {bucket}")
        entry = coverage[api]
        entry.setdefault("mutation_evidence", []).append(member)
        if BUCKET_ORDER.index(bucket) < BUCKET_ORDER.index(entry["bucket"]):
            entry["bucket"] = bucket
    return unmatched


def recompute_rollups(result: dict) -> None:
    """Recompute bucket counts and per-object/per-safety stats after merges."""

    members = result["members"]
    coverage = result["coverage"]
    bucket_counts = {bucket: 0 for bucket in BUCKET_ORDER}
    per_object: "OrderedDict[str, dict]" = OrderedDict()
    per_safety: "OrderedDict[str, dict]" = OrderedDict()
    for key, descriptor in members.items():
        bucket = coverage[key]["bucket"]
        bucket_counts[bucket] += 1
        obj_stats = per_object.setdefault(
            descriptor["object"], {b: 0 for b in BUCKET_ORDER} | {"total": 0}
        )
        obj_stats[bucket] += 1
        obj_stats["total"] += 1
        safety = descriptor["safety_class"] or "unclassified"
        safety_stats = per_safety.setdefault(
            safety, {b: 0 for b in BUCKET_ORDER} | {"total": 0}
        )
        safety_stats[bucket] += 1
        safety_stats["total"] += 1
    result["bucket_counts"] = bucket_counts
    result["per_object"] = per_object
    result["per_safety"] = per_safety


def _status_cell(bucket: str) -> str:
    return f"`{bucket}`"


def render_markdown(result: dict, inventory: dict, mutation_evidence: dict) -> str:
    total = result["total_members"]
    counts = result["bucket_counts"]
    covered = total - counts["uncovered"]
    accepted = counts["accepted_reviewed"]

    lines = [
        "# Protocol Corpus API Scope Tracker",
        "",
        "This tracker is generated by `tools/protocol-research/scope_tracker.py`.",
        "Do not edit it by hand; regenerate it after case-map, mutation-evidence",
        "or accepted-mapping changes.",
        "",
        f"- Denominator: `{total}` inventory members"
        " (the full TestedApplication API surface).",
        f"- Touched (any evidence): `{covered}` ({percent(covered, total)}).",
        f"- Confirmed (`accepted_reviewed`): `{accepted}` ({percent(accepted, total)}).",
        f"- Mutation-evidence source updated `{mutation_evidence.get('updated_at', 'unknown')}`.",
        "",
        "Only `accepted_reviewed` is a confirmed protocol claim. `accepted_seed`",
        "and `candidate` are planning signals. This is the honest progress view",
        "toward replacing the Vanessa Automation manager.",
        "",
        "## Progress By Safety Class",
        "",
        "| Safety class | Total | Accepted reviewed | Accepted seed | Candidate | Uncovered |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for safety, stats in result["per_safety"].items():
        lines.append(
            f"| `{safety}` | {stats['total']} | {stats['accepted_reviewed']} |"
            f" {stats['accepted_seed']} | {stats['candidate']} |"
            f" {stats['uncovered']} |"
        )
    lines.append(
        f"| **TOTAL** | **{total}** | **{counts['accepted_reviewed']}** |"
        f" **{counts['accepted_seed']}** | **{counts['candidate']}** |"
        f" **{counts['uncovered']}** |"
    )

    lines.extend(
        [
            "",
            "## Progress By Object",
            "",
            "| Object | Total | Accepted reviewed | Accepted seed | Candidate | Uncovered |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    for obj, stats in result["per_object"].items():
        lines.append(
            f"| `{obj}` | {stats['total']} | {stats['accepted_reviewed']} |"
            f" {stats['accepted_seed']} | {stats['candidate']} |"
            f" {stats['uncovered']} |"
        )

    lines.extend(
        [
            "",
            "## All Members",
            "",
            "Every inventory member with its current status and evidence.",
            "",
            "| API member | Kind | Safety class | Status | Evidence |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for key, descriptor in result["members"].items():
        entry = result["coverage"][key]
        evidence_bits: list[str] = []
        for mapping in entry.get("mappings", []):
            case_ids = ", ".join(mapping.get("case_ids", []))
            if case_ids:
                evidence_bits.append(case_ids)
        for mev in entry.get("mutation_evidence", []):
            path = mev.get("evidence_path")
            if path:
                evidence_bits.append(path)
        evidence = "; ".join(f"`{b}`" for b in evidence_bits) if evidence_bits else ""
        lines.append(
            f"| `{key}` | {descriptor.get('kind') or ''} |"
            f" `{descriptor.get('safety_class') or 'unclassified'}` |"
            f" {_status_cell(entry['bucket'])} | {evidence} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_tracker(
    inventory: dict, case_map: dict, mutation_evidence: dict
) -> tuple[dict, list[str]]:
    result = build_coverage(inventory, case_map)
    unmatched = list(result["unmatched_mappings"])
    unmatched += apply_mutation_evidence(result, mutation_evidence)
    recompute_rollups(result)
    result["unmatched_mappings"] = unmatched
    return result, unmatched


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--case-map", type=Path, default=DEFAULT_CASE_MAP)
    parser.add_argument(
        "--mutation-evidence", type=Path, default=DEFAULT_MUTATION_EVIDENCE
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--json-output", type=Path, default=None)
    args = parser.parse_args()

    inventory = load_json(args.inventory)
    case_map = load_json(args.case_map)
    mutation_evidence = (
        load_json(args.mutation_evidence)
        if args.mutation_evidence and args.mutation_evidence.exists()
        else {"members": []}
    )

    result, unmatched = build_tracker(inventory, case_map, mutation_evidence)

    markdown = render_markdown(result, inventory, mutation_evidence)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8", newline="\n")

    counts = result["bucket_counts"]
    print(f"scope-tracker={args.output}")
    print(
        "scope-summary: total={total} accepted_reviewed={ar} accepted_seed={as_}"
        " candidate={c} uncovered={u}".format(
            total=result["total_members"],
            ar=counts["accepted_reviewed"],
            as_=counts["accepted_seed"],
            c=counts["candidate"],
            u=counts["uncovered"],
        )
    )

    if args.json_output:
        summary = {
            "schema": "qa-mcp.api-scope-tracker-summary.v1",
            "total_members": result["total_members"],
            "bucket_counts": counts,
            "unmatched": unmatched,
        }
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(
            json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )

    if unmatched:
        print("scope-error: unmatched members: " + ", ".join(unmatched))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
